In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [14]:
data = pd.read_csv('../data/household_power_consumption.txt',sep=';')

C:\Users\Kartik\AppData\Local\Temp\ipykernel_17660\63241992.py:1: DtypeWarning: Columns (2: Global_active_power, 3: Global_reactive_power, 4: Voltage, 5: Global_intensity, 6: Sub_metering_1, 7: Sub_metering_2) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('../data/household_power_consumption.txt',sep=';')

In [38]:
data.head()

,date,time,global_active_power,global_reactive_power,voltage,global_intensity,sub_metering_1,sub_metering_2,sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0

<h2>Basic Data Evaluation</h2>

In [17]:
data.shape

(2075259, 9)

In [18]:
data.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='str')

In [21]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   date                   str
 1   time                   str
 2   global_active_power    object
 3   global_reactive_power  object
 4   voltage                object
 5   global_intensity       object
 6   sub_metering_1         object
 7   sub_metering_2         object
 8   sub_metering_3         float64
dtypes: float64(1), object(6), str(2)
memory usage: 142.5+ MB

In [20]:
data.columns=data.columns.str.lower().str.strip()

In [22]:
data.isna().sum()

date                         0
time                         0
global_active_power          0
global_reactive_power        0
voltage                      0
global_intensity             0
sub_metering_1               0
sub_metering_2               0
sub_metering_3           25979
dtype: int64

In [25]:
data['global_active_power']

0          4.216
1          5.360
2          5.374
3          5.388
4          3.666
           ...
2075254    0.946
2075255    0.944
2075256    0.938
2075257    0.934
2075258    0.932
Name: global_active_power, Length: 2075259, dtype: object

In [26]:
data[data['sub_metering_3'].isna()]

,date,time,global_active_power,global_reactive_power,voltage,global_intensity,sub_metering_1,sub_metering_2,sub_metering_3
6839,21/12/2006,11:23:00,?,?,?,?,?,?,NaN
6840,21/12/2006,11:24:00,?,?,?,?,?,?,NaN
19724,30/12/2006,10:08:00,?,?,?,?,?,?,NaN
19725,30/12/2006,10:09:00,?,?,?,?,?,?,NaN
41832,14/1/2007,18:36:00,?,?,?,?,?,?,NaN
...,...,...,...,...,...,...,...,...,...
1990185,28/9/2010,19:09:00,?,?,?,?,?,?,NaN
1990186,28/9/2010,19:10:00,?,?,?,?,?,?,NaN
1990187,28/9/2010,19:11:00,?,?,?,?,?,?,NaN
1990188,28/9/2010,19:12:00,?,?,?,?,?,?,NaN
2027411,24/10/2010,15:35:00,?,?,?,?,?,?,NaN

In [29]:
data.eq('?').sum()

date                         0
time                         0
global_active_power      25979
global_reactive_power    25979
voltage                  25979
global_intensity         25979
sub_metering_1           25979
sub_metering_2           25979
sub_metering_3               0
dtype: int64

In [36]:
data=data.replace('?',np.nan)

In [37]:
data.isna().sum()

date                         0
time                         0
global_active_power      25979
global_reactive_power    25979
voltage                  25979
global_intensity         25979
sub_metering_1           25979
sub_metering_2           25979
sub_metering_3           25979
dtype: int64